services:
  - type: web
    name: background-remover
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appp:app
    envVars:
      - key: PORT
        value: 8000
